# Development-only typed adapters. Never compile a stale generated native copy.
set(_mmvr_state_files)
set(_mmvr_state_declarations "#include \"2s2h/VR/NativeStateVisitor.h\"\n")
set(_mmvr_state_calls "")
foreach(_file IN LISTS ALL_FILES)
  get_filename_component(_absolute "${_file}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  file(RELATIVE_PATH _relative "${CMAKE_CURRENT_SOURCE_DIR}/src" "${_absolute}")
  if(NOT _relative MATCHES "^\\.\\./" AND _relative MATCHES "\\.c$")
    string(SHA256 _hash "${_relative}")
    string(SUBSTRING "${_hash}" 0 16 _key)
    set(_wrapper "${CMAKE_CURRENT_LIST_DIR}/native_generated/${_key}.c")
    if(NOT EXISTS "${_wrapper}")
      message(FATAL_ERROR "Native state inventory missing: ${_relative}")
    endif()
    set(_local_metadata "${CMAKE_CURRENT_LIST_DIR}/native_locals/${_key}.json")
    if(EXISTS "${_local_metadata}")
      file(READ "${_local_metadata}" _metadata)
      string(JSON _expected GET "${_metadata}" sourceSha256)
      file(SHA256 "${_absolute}" _actual)
      if(NOT _expected STREQUAL _actual)
        message(FATAL_ERROR "Stale state adapter for ${_relative}. Regenerate with tools/state-local-storage.py --source ${_relative}, then tools/state-native-catalog.py --stage.")
      endif()
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_absolute}" "${_local_metadata}")
    endif()
    set(_file "${_wrapper}")
    string(APPEND _mmvr_state_declarations "void MMVR_StateVisit_${_key}(MMVR_StateSink*);\n")
    string(APPEND _mmvr_state_calls "MMVR_StateVisit_${_key}(sink);\n")
  endif()
  list(APPEND _mmvr_state_files "${_file}")
endforeach()
set(ALL_FILES ${_mmvr_state_files})
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/mmvr-state-providers.c" "${_mmvr_state_declarations}\nvoid MMVR_VisitNativeState(MMVR_StateSink* sink) {\n${_mmvr_state_calls}}\n")
list(APPEND ALL_FILES "${CMAKE_CURRENT_BINARY_DIR}/mmvr-state-providers.c")
