# Pinned, source-built Android dependencies; all FetchContent files stay in the build root.
include(FetchContent)
set(BUILD_TESTING OFF CACHE BOOL "Dependency tests" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Static dependencies" FORCE)
set(SDL_SHARED ON CACHE BOOL "SDLActivity loads libSDL2" FORCE)
set(SDL_STATIC OFF CACHE BOOL "Use one SDL instance" FORCE)
FetchContent_Declare(SDL2 GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG release-2.32.10 GIT_SHALLOW TRUE OVERRIDE_FIND_PACKAGE)
FetchContent_MakeAvailable(SDL2)
set(SDL2NET_SAMPLES OFF CACHE BOOL "No SDL2_net sample programs" FORCE)
set(SDL2NET_INSTALL OFF CACHE BOOL "No SDL2_net install target" FORCE)
set(BUILD_SHARED_LIBS ON CACHE BOOL "SDL2_net links to SDL2 shared" FORCE)
FetchContent_Declare(SDL2_net GIT_REPOSITORY https://github.com/libsdl-org/SDL_net.git GIT_TAG release-2.2.0 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(SDL2_net)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Static dependencies" FORCE)
set(INSTALL_DOCS OFF CACHE BOOL "No dependency docs" FORCE)
FetchContent_Declare(ogg GIT_REPOSITORY https://github.com/xiph/ogg.git GIT_TAG v1.3.5 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(ogg)
set(OGG_INCLUDE_DIR "${ogg_SOURCE_DIR}/include;${ogg_BINARY_DIR}/include" CACHE STRING "Android Ogg headers" FORCE)
set(OGG_LIBRARY ogg CACHE STRING "Android Ogg target" FORCE)
set(PNG_SHARED OFF CACHE BOOL "Static PNG" FORCE)
set(PNG_TESTS OFF CACHE BOOL "No PNG tests" FORCE)
set(PNG_TOOLS OFF CACHE BOOL "No PNG tools" FORCE)
FetchContent_Declare(png GIT_REPOSITORY https://github.com/pnggroup/libpng.git GIT_TAG v1.6.47 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(png)
FetchContent_Declare(vorbis GIT_REPOSITORY https://github.com/xiph/vorbis.git GIT_TAG v1.3.7 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(vorbis)
FetchContent_Declare(opus GIT_REPOSITORY https://github.com/xiph/opus.git GIT_TAG v1.5.2 GIT_SHALLOW TRUE)
set(OPUS_BUILD_PROGRAMS OFF CACHE BOOL "No opus tools" FORCE)
FetchContent_MakeAvailable(opus)
FetchContent_Declare(opusfile GIT_REPOSITORY https://github.com/xiph/opusfile.git GIT_TAG v0.12 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(opusfile)
add_library(opusfile STATIC ${opusfile_SOURCE_DIR}/src/info.c ${opusfile_SOURCE_DIR}/src/internal.c ${opusfile_SOURCE_DIR}/src/opusfile.c ${opusfile_SOURCE_DIR}/src/stream.c)
target_compile_definitions(opusfile PRIVATE OP_DISABLE_HTTP)
target_include_directories(opusfile PUBLIC ${opusfile_SOURCE_DIR}/include ${opus_SOURCE_DIR}/include)
target_link_libraries(opusfile PUBLIC opus ogg)
# Native game headers use the installed <opus/...> namespace; retain it in the build tree.
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/codec-include/opus")
file(COPY "${opus_SOURCE_DIR}/include/" "${opusfile_SOURCE_DIR}/include/" DESTINATION "${CMAKE_BINARY_DIR}/codec-include/opus" FILES_MATCHING PATTERN "*.h")
target_include_directories(opusfile PUBLIC "${CMAKE_BINARY_DIR}/codec-include")
set(BUILD_API_LAYERS OFF CACHE BOOL "No OpenXR layers" FORCE)
set(BUILD_TESTS OFF CACHE BOOL "No OpenXR tests" FORCE)
set(BUILD_CONFORMANCE_TESTS OFF CACHE BOOL "No OpenXR conformance" FORCE)
set(BUILD_ALL_EXTENSIONS ON CACHE BOOL "OpenXR extensions" FORCE)
set(INSTALL_TO_ARCHITECTURE_PREFIXES OFF CACHE BOOL "Local OpenXR build" FORCE)
FetchContent_Declare(openxr GIT_REPOSITORY https://github.com/KhronosGroup/OpenXR-SDK.git GIT_TAG release-1.1.60 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(openxr)
